### ISSUE TITLE
Master (1st person joined into instance) not appeared on Earth until next sync happen

### ISSUE THREAD

**Issue by slord399** [JLChnToZ/vrctzhologram#3]
When I testing this, I found that master seems to be not shown on non-master users.
It can be either repaired by,
*Wait for next sync period
*Re-join to instance

but would be better to have sync method to prevent this issue.
(Only happen to master so maybe MasterOnly trigger to push time zone data to others could be when they joined..)

**Comment by JLChnToZ** [comment]
Do you mean a resync button to grab the players' data again?

**Comment by slord399** [comment]
Re-sync button should also works well.
Issue is basically non-master cannot see master on the Earth cube until next update.
(between non-master can see all of others time)


It only happen to master as it seems so something to push sync of master when non-master joined be fixing issue.
(still thinking best option to take so I leave it to you for your idea of resolving issue as well.)

**Comment by JLChnToZ** [comment]
Oh thanks for the hints, I know the reason now, but I need to figure out the better way to do it.

The current way to get in sync is just putting the user's own data to the specified field and pass the ownership to the next player until a round is over. The bug here is when the second player is in, the master is already passing the ownership to the second player so the first's data is likely to be ignored by the others.

**Comment by slord399** [comment]
ahh, that's makes sense. yeah.
