### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by FoxFireVR** [JLChnToZ/vrctzhologram#5]
when i load the unity file into unity i get 72 script errors for poiyomi, any ideas or quick fixes , using poi pro 7.345

**Comment by slord399** [comment]
This is not repo for poiyomi shader. You better ask at official discord at discord.gg/poiyomi

Let me guess that your SDK maybe more than few month old could be.
If this not resolve your issue, just head to poiyomi shader discord.

**Comment by FoxFireVR** [comment]
My SDK is the newest there is , and I have no issue with poiyomi shaders till I loaded your timezone asset, and when I removed it the poiyomi errors went away, I seen your timezone globe in many world's and I love it and want to use it, I'm just having issues and don't know what to do

**Comment by slord399** [comment]
I suggest you post full error and warning screenshot (not text, picture be best) as we need to check what's going on on your editor.

**Comment by FoxFireVR** [comment]
I will post pic in 5ish hours when I finish streaming

**Comment by JLChnToZ** [comment]
Please give out your error messages to investigate, as I know there should be no conflict with Poiyomi Shaders, even in demo world I have penlights that is using Poiyomi. Wondering have you got anything else imported to your project such as original version of the hologram shader?

**Comment by FoxFireVR** [comment]
![cXNfD8j](https://user-images.githubusercontent.com/87218872/153424252-17508518-fea7-4a47-af38-298269d1f494.png)

**Comment by JLChnToZ** [comment]
Did you got any error messages come out from elsewhere? I don't find anything informative from your screenshot...

**Comment by FoxFireVR** [comment]
no those are only spot i get error and they happen soon as i load time zone thing in , i tried reimporting poi shaders after but same issue, and cause so much uses poi in my scene when i delete shaders i get more errors , but soon as i delete thetime zone thing i have no errors

**Comment by JLChnToZ** [comment]
And may I ask what Unity version / SDK version and U# version you are using?

**Comment by FoxFireVR** [comment]
udon sharp v0.20.3, VRCSDK3-WORLD-2021.11.24.16.19, unity 2019.4.31f1

**Comment by JLChnToZ** [comment]
Ahh, I spot the problem when I tried to import Poiyomi Pro. It is because the Hologram Shader I adopted has a struct called `Foldout` without namespace, which conflicts with Poiyomi's (C# thing, types without namespace have higher priority to match when the name is the same)

https://github.com/JLChnToZ/vrctzhologram/blob/31ae64be0a51e04e9b11289fd80d1f942b72848a/TZSyncHologram/Assets/TimeZoneSyncHologram/Scripts/Editor/HologramShaderGUI.cs#L355

For temporary quick fixes, you can add a C# namespace on the file above or just replace `Foldout` to something else except `EditorGUI.Foldout` yourself.

I will make a patch in here too to avoid future conflicts.

**Comment by JLChnToZ** [comment]
For now, I'll close this issue, if you have any problem about this even applied the patched version, please feel free to reopen, thanks.
